### PR TITLE
Use XDG_CONFIG_HOME env var instead of hardcoded ~/.config path

### PR DESCRIPTION
**Pull request by msunith**
Better to use the env var XDG_CONFIG_HOME instead of hardcoded path  ~/.config. Will be useful for people who like to create vim config files under custom location

### CODE REVIEW

**Comment by taigacute** [comment]
what about use `$VIMPATH` ? or we can judge whether` $XDG_CONFIG_HOME `is set.if set use it .

**Comment by msunith** [comment]
Good points. Give me some time. I will update the pull request

**Comment by taigacute** [comment]
set the `$CONFIG`
```VIML
let $PLUGINCONFIGPATH = expand(($XDG_CONFIG_HOME ? $XDG_CONFIG_HOME : $VIMPATH).'/core/plugins')
```
then in yaml we can use it like this 
```viml
- repo: xxx/xxx
  hook_source: $PLUGCONFIGPATH/xxx.vim
```

**Comment by taigacute** [comment]
use `$VIMPATH`, so you git clone to your `XDG_CONFIG`

**Pull request closed without merging**
